#ifndef LIB_FILE_H
#define LIB_FILE_H

#include <chrono>
#include <filesystem>
#include <fstream>
#include <string>
#include <unordered_set>

#include "nlohmann/json.hpp"
#include "si2dr_liberty.h"
#include "spdlog/sinks/basic_file_sink.h"
#include "spdlog/sinks/stdout_color_sinks.h"
#include "spdlog/spdlog.h"

#include "Iterators.hpp"
#include "json_utils.hpp"
#include "verilog_utils.hpp"
#include "version.h"

using json = nlohmann::json;

class LibFile {
public:
  LibFile(const std::string &filepath, const std::string &loggername);
  ~LibFile();
  std::shared_ptr<spdlog::logger> logger_;
  std::filesystem::path filepath_; // full path to the file
  std::string basename_;           // file name without extension
  std::string filename_;           // full file name with extension
  std::string libname_ = "";       // library name obtained through parsing
  std::string jsonname_ = "";      // json file name to store parsed data
  std::string loggername_ = "";    // log file name
  json lib_json_ = json::object();
  void writeJsonToFile();
  void parse();
  void modify();
  void mono(const bool is_slew);
  void supercell(const int chain_length, const std::vector<std::string> &cell_names);
  void verilog(const int chain_length, const std::vector<std::string> &cell_names);
  void spice(const int chain_length, const std::vector<std::string> &cell_names,
             const std::string &verilog_lib_file, const std::string &spice_lib_file);
  std::map<std::string, std::string> logic(const std::string &cell_name);

private:
  si2drErrorT err_;
  int process_ = 0;
  float voltage_ = 0.0;
  int temperature_ = 0;
  void read();
  bool checkTimingArcMonotonicity(const json &cell, const json &pin, const json &arc,
                                  const std::string &type, bool is_slew);
  // --- Private Helper Methods ---

  // Helper function to split a string by whitespace
  std::vector<std::string> splitString(const std::string &s);

  // Function to generate RC lines based on instance index and stage
  void generateRCLines(std::ofstream &outFile, const std::string &netName, int instanceIndex,
                       bool isFinalStage);

  // Function to modify the SPICE netlist generated by v2lvs
  bool modifySpiceNetlist(const std::string &v2lvsSpiceFile, // Input is the v2lvs output
                          const std::string &finalSpiceFile, // Output is the final file
                          const std::string &targetGlobalLine);
};

#endif // LIB_FILE_H