// version.h.in
#pragma once

// Auto-generated by CMake - DO NOT EDIT
#define APP_NAME          "ZlibValidation"
#define APP_VERSION_MAJOR 1
#define APP_VERSION_MINOR 1
#define APP_VERSION_PATCH 3
#define APP_VERSION       "1.1.3"
#define APP_AUTHOR        "Song Zixuan (宋子轩)"
#define APP_CONTACT       "zx.song@zju.edu.cn, songcedar@outlook.com"
#define BUILD_TIMESTAMP   "2026-05-13 10:47:32"
