// version.h.in
#pragma once

// Auto-generated by CMake - DO NOT EDIT
#define APP_NAME          "ZlibValidation"
#define APP_VERSION_MAJOR 0
#define APP_VERSION_MINOR 1
#define APP_VERSION_PATCH 0
#define APP_VERSION       "0.1.0"
#define APP_AUTHOR        "Song Zixuan"
#define APP_CONTACT       "cedar@zju.edu.cn"
#define BUILD_TIMESTAMP   "2025-03-28 09:43:58"
