#include <chrono>
#include <filesystem>
#include <fstream>
#include <iostream>

#include "spdlog/spdlog.h"
#include <tabulate/markdown_exporter.hpp>

#include "compare.hpp"
#include "version.h"

/**
 * @brief Constructs a LibraryComparator object.
 *
 * This constructor initializes a LibraryComparator object by loading and parsing
 * JSON files associated with the provided reference and comparison library files.
 * If the JSON files do not exist, they are generated by parsing the library files.
 *
 * @param ref_libfile Reference to the reference library file object.
 * @param comp_libfile Reference to the comparison library file object.
 * @param reltol Relative tolerance value for comparison.
 */
LibraryComparator::LibraryComparator(LibFile &ref_libfile, LibFile &comp_libfile, double reltol,
                                     double abstol)
    : reltol_(reltol), abstol_(abstol) {
  std::string ref_json_name = ref_libfile.basename_ + ".json";
  if (!std::filesystem::exists(ref_json_name)) {
    spdlog::info("Reference JSON file {} not found. Parsing first.", ref_json_name);
    ref_libfile.parse();
    ref_libfile.writeJsonToFile();
    ref_json_ = ref_libfile.lib_json_;
  } else {
    // Read the JSON file into json object
    std::ifstream ref_in(ref_json_name);
    if (!ref_in.is_open()) {
      spdlog::error("Could not open file '{}' for reading", ref_json_name);
      return;
    }
    try {
      ref_json_ = json::parse(ref_in);
    } catch (const json::parse_error &e) {
      spdlog::error("Error parsing reference JSON file '{}': {}", ref_json_name, e.what());
      return;
    }
  }
  std::string comp_json_name = comp_libfile.basename_ + ".json";
  if (!std::filesystem::exists(comp_json_name)) {
    spdlog::info("Comparison JSON file {} not found. Parsing first.", comp_json_name);
    comp_libfile.parse();
    comp_libfile.writeJsonToFile();
    comp_json_ = comp_libfile.lib_json_;
  } else {
    // Read the JSON file into json object
    std::ifstream comp_in(comp_json_name);
    if (!comp_in.is_open()) {
      spdlog::error("Could not open file '{}' for reading", comp_json_name);
      return;
    }
    try {
      comp_json_ = json::parse(comp_in);
    } catch (const json::parse_error &e) {
      spdlog::error("Error parsing comparison JSON file '{}': {}", comp_json_name, e.what());
      return;
    }
  }

  ref_lib_path_ = ref_libfile.filepath_;
  comp_lib_path_ = comp_libfile.filepath_;
  spdlog::info("Successfully loaded JSON files for comparison");
}

void LibraryComparator::compareLut(const std::string &cell_name, const std::string &pin_name,
                                   const std::string &timing_type, const std::string &related_pin,
                                   const std::string &arc_name, const json &ref_lut,
                                   const json &comp_lut, Table &table) {
  spdlog::info("Comparing LUT of '{}' ...", arc_name);
  std::vector<double> ref_index_1 = ref_lut["index_1"].get<std::vector<double>>();
  std::vector<double> ref_index_2 = ref_lut["index_2"].get<std::vector<double>>();
  std::vector<double> comp_index_1 = comp_lut["index_1"].get<std::vector<double>>();
  std::vector<double> comp_index_2 = comp_lut["index_2"].get<std::vector<double>>();
  if (ref_index_1 != comp_index_1 || ref_index_2 != comp_index_2) {
    spdlog::warn("Mismatch in LUT indices for '{}' in cell: '{}', pin: '{}', related_pin: '{}', "
                 "timing_type: '{}'",
                 arc_name, cell_name, pin_name, related_pin, timing_type);
    return;
  } else {
    spdlog::debug("LUT indices match for '{}'", arc_name);

    std::vector<std::vector<double>> comp_value_matrix;
    // Generate a matrix of values from the JSON array for comparison library
    for (const auto &row_val : comp_lut["values"]) {
      std::vector<double> row_data;
      // Check if the row value is an array
      if (!row_val.is_array()) {
        spdlog::error("Invalid LUT format: '{}' values should be an array of arrays in comp_lib '{}', "
                      "cell '{}', pin '{}', "
                      "related_pin '{}', timing_type '{}'",
                      arc_name, this->comp_lib_path_.string(), cell_name, pin_name, related_pin,
                      timing_type);
        return;
      }
      // Check if non-numeric values
      for (const auto &val : row_val) {
        if (val.is_number()) {
          row_data.push_back(val.get<double>());
        } else {
          spdlog::error(
              "Non-numeric value found in '{}'.values, skipping value: {} in comp_lib '{}', cell '{}', "
              "pin '{}', related_pin '{}', timing_type '{}'",
              arc_name, val.dump(), this->comp_lib_path_.string(), cell_name, pin_name, related_pin,
              timing_type);
          return;
        }
      }
      comp_value_matrix.push_back(row_data);
    }
    // Generate a matrix of values from the JSON array for reference library
    std::vector<std::vector<double>> ref_value_matrix;
    for (const auto &row_val : ref_lut["values"]) {
      std::vector<double> row_data;
      // Check if the row value is an array
      if (!row_val.is_array()) {
        spdlog::error("Invalid LUT format: '{}' values should be an array of arrays in ref_lib '{}', "
                      "cell '{}', pin '{}', "
                      "related_pin '{}', timing_type '{}'",
                      arc_name, this->ref_lib_path_.string(), cell_name, pin_name, related_pin,
                      timing_type);
        return;
      }
      // Check if non-numeric values
      for (const auto &val : row_val) {
        if (val.is_number()) {
          row_data.push_back(val.get<double>());
        } else {
          spdlog::error(
              "Non-numeric value found in '{}'.values, skipping value: {} in ref_lib '{}', cell '{}', "
              "pin '{}', related_pin '{}', timing_type '{}'",
              arc_name, val.dump(), this->ref_lib_path_.string(), cell_name, pin_name, related_pin,
              timing_type);
          return;
        }
      }
      ref_value_matrix.push_back(row_data);
    }
    // Compare the matrix for relative tolerance
    if (!comp_value_matrix.empty() && !comp_value_matrix[0].empty()) {
      for (size_t i = 0; i < comp_value_matrix.size(); ++i) {
        for (size_t j = 0; j < comp_value_matrix[i].size(); ++j) {
          double ref_val = ref_value_matrix[i][j];
          double comp_val = comp_value_matrix[i][j];
          if (std::abs(ref_val - comp_val) > reltol_ * std::abs(ref_val) &&
              std::abs(ref_val - comp_val) > abstol_) {
            // TODO: Found a outlier
            spdlog::debug("LUT value mismatch for '{}', index_1: {}, index_2: {}", arc_name,
                          ref_index_1[i], ref_index_2[j]);
            table.add_row({related_pin + "->" + pin_name, std::to_string(ref_val),
                           std::to_string(comp_val), std::to_string(comp_val - ref_val),
                           std::to_string((comp_val - ref_val) / ref_val * 100), timing_type, arc_name,
                           std::to_string(i + 1), std::to_string(ref_index_1[i]), std::to_string(j + 1),
                           std::to_string(ref_index_2[j]), "<"});
            spdlog::debug("table size: {}", table.size());
          } else {
            spdlog::debug("LUT value match for '{}', index_1: {}, index_2: {}", arc_name, ref_index_1[i],
                          ref_index_2[j]);
          }
        }
      }
    } else {
      spdlog::error(
          "Empty or invalid 'values' array found for cell: '{}', pin: '{}', related_pin: '{}', "
          "timing_type: '{}', arc: '{}'",
          cell_name, pin_name, related_pin, timing_type, arc_name);
    }
  }
}

void LibraryComparator::compareTimingArc(const std::string &cell_name, const std::string &pin_name,
                                         const std::string &timing_type, const json &ref_timing_arc,
                                         const json &comp_timing_arc, Table &table) {
  spdlog::info("Comparing timing type '{}' ...", timing_type);

  std::string related_pin = ref_timing_arc["related_pin"].get<std::string>();
  spdlog::debug("Related pin: '{}'", related_pin);

  std::vector<std::string> arc_names = {"cell_rise", "cell_fall", "rise_transition", "fall_transition"};
  for (auto arc_name : arc_names) {
    if (comp_timing_arc.contains(arc_name)) {
      spdlog::debug("Comparing timing arc: '{}'", arc_name);
      // Look for the arc in the reference JSON
      if (ref_timing_arc.contains(arc_name)) {
        // Found this arc
        spdlog::debug("Found timing arc: '{}'", arc_name);
        compareLut(cell_name, pin_name, timing_type, related_pin, arc_name, ref_timing_arc[arc_name],
                   comp_timing_arc[arc_name], table);
      } else {
        // arc not found in reference JSON
        spdlog::warn("Timing arc: '{}' not found in reference JSON", arc_name);
      }
    }
  }
}

void LibraryComparator::comparePin(const std::string &cell_name, const std::string &pin_name,
                                   const json &ref_pin, const json &comp_pin, Table &table) {
  spdlog::info("Comparing pin '{}' ...", pin_name);

  if (comp_pin.contains("timing_arcs")) {
    for (const auto &comp_arc : comp_pin["timing_arcs"]) {
      std::string timing_type = comp_arc["timing_type"].get<std::string>();
      spdlog::debug("Comparing timing type: '{}'", timing_type);
      // Look for the timing type in the reference JSON
      auto ref_arc_it = std::find_if(
          ref_pin["timing_arcs"].begin(), ref_pin["timing_arcs"].end(),
          [&timing_type](const json &ref_arc) { return ref_arc["timing_type"] == timing_type; });
      if (ref_arc_it != ref_pin["timing_arcs"].end()) {
        // Found this timing type
        spdlog::debug("Found timing type: '{}'", timing_type);
        compareTimingArc(cell_name, pin_name, timing_type, *ref_arc_it, comp_arc, table);
      } else {
        // timing arc not found in reference JSON
        spdlog::warn("Timing arc: '{}' not found in reference JSON", timing_type);
      }
    }
  } else {
    spdlog::info("No timing arcs found for pin: '{}'", comp_pin["pin_name"].get<std::string>());
  }
}

void LibraryComparator::compareCell(const std::string &cell_name, const json &ref_cell,
                                    const json &comp_cell, Table &table) {
  spdlog::info("Comparing cell '{}' ...", cell_name);

  if (comp_cell.contains("output_pins")) {
    for (const auto &comp_pin : comp_cell["output_pins"]) {
      std::string pin_name = comp_pin["pin_name"].get<std::string>();
      spdlog::debug("Comparing pin: '{}'", pin_name);
      // Look for the pin in the reference JSON
      auto ref_pin_it =
          std::find_if(ref_cell["output_pins"].begin(), ref_cell["output_pins"].end(),
                       [&pin_name](const json &ref_pin) { return ref_pin["pin_name"] == pin_name; });
      if (ref_pin_it != ref_cell["output_pins"].end()) {
        // Found this pin
        spdlog::debug("Found pin: '{}'", pin_name);
        comparePin(cell_name, pin_name, *ref_pin_it, comp_pin, table);
      } else {
        // pin not found in reference JSON
        spdlog::warn("Pin: '{}' not found in reference JSON", pin_name);
      }
    }
  } else {
    spdlog::info("No output pins found for cell: '{}'", cell_name);
  }
}

void LibraryComparator::generateReport(const std::string &output_file) {
  std::ofstream outfile(output_file);
  outfile << "# LIBRARY comparison\n" << std::endl;
  outfile << "**Reference library: " << ref_lib_path_ << "**\n" << std::endl;
  outfile << "**Comparison library: " << comp_lib_path_ << "**\n" << std::endl;
  outfile << "**Absolute tolerance: " << abstol_ << "**\n" << std::endl;
  outfile << "**Relative tolerance: " << reltol_ << "**\n" << std::endl;
  outfile << "**Performed by " << APP_NAME << " v" << APP_VERSION << " from " << APP_AUTHOR;
  auto now = std::chrono::system_clock::now();
  std::time_t now_time_t = std::chrono::system_clock::to_time_t(now);
  std::tm *now_tm = std::localtime(&now_time_t);
  outfile << ". on: " << std::put_time(now_tm, "%c") << "**\n" << std::endl;
  outfile << "> Legend: < outlier, * scaled, ! indices switched, ^ slews extrapolated, ~ loads "
             "extrapolated,\n";
  outfile << "> \n";
  outfile
      << "> Legend: + padding added, /0 divide by zero, / slews interpolated, # loads interpolated\n";
  outfile << "> \n";
  outfile << "> Legend: << value is less but unknown, >> value is more but unknown\n\n";

  spdlog::info("Starting comparison report generation ...");
  for (const auto &comp_cell : comp_json_["cells"]) {
    std::string cell_name = comp_cell["cell_name"].get<std::string>();
    spdlog::debug("Comparing cell: '{}'", cell_name);
    // Look for the cell in the reference JSON
    auto ref_cell_it =
        std::find_if(ref_json_["cells"].begin(), ref_json_["cells"].end(),
                     [&cell_name](const json &ref_cell) { return ref_cell["cell_name"] == cell_name; });
    if (ref_cell_it != ref_json_["cells"].end()) {
      // Found this cell
      spdlog::debug("Found cell: '{}'", cell_name);
      Table table;
      table.add_row({"Pin Name", "Reference", "Comparison", "Diff", "Diff %", "Type", "Arc Name",
                     "Row #", "Index_1", "Col #", "Index_2", "Note"});
      // Header formatting
      for (size_t i = 0; i < table[0].size(); ++i) {
        table[0][i].format().font_color(Color::yellow).font_style({FontStyle::bold});
      }
      compareCell(cell_name, *ref_cell_it, comp_cell, table);

      if (table.size() > 1) {
        // Data starts from row 1, row 0 is header
        size_t failed_count = table.size() - 1;
        double sum_diff = 0.0;
        double sum_diff_percent = 0.0;
        size_t outlier_count = 0;
        double max_diff = -1e9;
        double max_diff_percent = -1e9;
        std::vector<double> diff_values; // Store diff values for std deviation calculation

        // Index of columns
        const int diff_index = 3;
        const int diff_percent_index = 4;
        const int note_index = 11;

        for (size_t i = 1; i < table.size(); ++i) {
          try {
            double diff = std::stod(table[i][diff_index].get_text());
            double diff_percent = std::stod(table[i][diff_percent_index].get_text());

            sum_diff += diff;
            sum_diff_percent += diff_percent;
            diff_values.push_back(diff_percent);

            if (table[i][note_index].get_text() == "<") {
              outlier_count++;
            }
            max_diff = std::max(max_diff, diff);
            max_diff_percent = std::max(max_diff_percent, diff_percent);

          } catch (const std::invalid_argument &e) {
            spdlog::error("Could not convert value to double: {}", e.what());
            continue; // Skip this row if there's an error
          }
        }

        double avg_diff = sum_diff / failed_count;
        double avg_diff_percent = sum_diff_percent / failed_count;

        outfile << "## " << cell_name << "\n\n";
        outfile << "Delay Comparison in ns\n\n";
        if (output_file.substr(output_file.size() - 3) == ".md") {
          MarkdownExporter exporter;
          auto markdown = exporter.dump(table);
          outfile << markdown << std::endl;
        } else {
          outfile << table << std::endl;
        }
        outfile << std::endl;
        std::cout << table << std::endl;
        outfile << cell_name << " delay SUMMARY (abstol: " << abstol_ << ", reltol: " << reltol_
                << ")\n";

        // Create summary table
        Table summary_table;
        summary_table.add_row({"Cell Name", "Data Type", "Failed Count", "Avg Diff", "Avg Diff%",
                               "Max Diff", "Max Diff%", "Outliers"});
        summary_table.add_row({cell_name, "delay(ns)", std::to_string(failed_count),
                               std::to_string(avg_diff), std::to_string(avg_diff_percent) + "%",
                               std::to_string(max_diff), std::to_string(max_diff_percent) + "%",
                               std::to_string(outlier_count)});

        // Output summary table
        if (output_file.substr(output_file.size() - 3) == ".md") {
          MarkdownExporter exporter;
          auto markdown = exporter.dump(summary_table);
          outfile << markdown << std::endl;
        } else {
          outfile << summary_table << std::endl;
        }
        outfile << "Worst delay outlier: Max Abs: " << max_diff << ", Max Rel: " << max_diff_percent
                << "%, Outliers: " << outlier_count << "\n\n";
      }
    } else {
      // cell not found in reference JSON
      spdlog::warn("Cell: '{}' not found in reference JSON", cell_name);
    }
  }

  outfile.close();
}