name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Doxygen
        uses: jendrikseipp/setup-doxygen@v1
        with:
          doxygen-version: '1.9.5'

      - name: Generate Documentation
        run: |
          doxygen Doxyfile # 直接在根目录执行 Doxygen 命令，输出到 doc_doxygen 目录

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: doc_doxygen
          clean: true # 每次部署前清理 gh-pages 分支
          commit-message: "Deploy documentation from ${{ github.ref_name }} [${{ github.sha }}]"